CREATE TABLE `testlab-db`.cycle_casted (
	test_id INT UNSIGNED NOT NULL DEFAULT 0,
	seq_id INT UNSIGNED DEFAULT NULL,
	computer_name VARCHAR(20) DEFAULT NULL COMMENT 'length 20',
	chl_id VARCHAR(20) DEFAULT NULL COMMENT 'length 20', 
	barcode VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'length 60',
	cycle_id INT UNSIGNED NOT NULL DEFAULT 0, 
	charge_capacity DOUBLE DEFAULT NULL COMMENT 'unit Ah',
	discharge_capacity DOUBLE DEFAULT NULL COMMENT 'unit Ah',
	charge_energy DOUBLE DEFAULT NULL COMMENT 'unit Wh', 
	discharge_energy DOUBLE DEFAULT NULL COMMENT 'unit Wh',
	net_discharge_capacity DOUBLE DEFAULT NULL COMMENT 'unit Ah', 
	net_discharge_energy DOUBLE DEFAULT NULL COMMENT 'unit Wh', 
	charge_mid_voltage DOUBLE DEFAULT NULL COMMENT 'unit V', 
	discharge_mid_voltage DOUBLE DEFAULT NULL COMMENT 'unit V',
	batch_no VARCHAR(60) DEFAULT NULL COMMENT 'length 60',
	remark VARCHAR(60) DEFAULT NULL COMMENT 'length 60',
	soh DOUBLE DEFAULT NULL COMMENT 'unit %', 
	specific_charge_capacity DOUBLE DEFAULT NULL COMMENT 'unit mAh/g', 
	specific_discharge_capacity DOUBLE DEFAULT NULL COMMENT 'unit mAh/g',
	specific_charge_energy DOUBLE DEFAULT NULL COMMENT 'unit mWh/g', 
	specific_discharge_energy DOUBLE DEFAULT NULL COMMENT 'unit mWh/g',
	staring_time BIGINT DEFAULT NULL,
	end_time BIGINT DEFAULT NULL,
	builder VARCHAR(25) DEFAULT NULL COMMENT 'length 25',
	active_material DOUBLE DEFAULT NULL COMMENT 'unit mg', 
	#active_material_unit VARCHAR(10) DEFAULT NULL COMMENT 'length 10',
	dicharge_capacity_attenuation_rate DOUBLE DEFAULT NULL COMMENT 'unit %', 
	discharge_energy_retention_rate DOUBLE DEFAULT NULL COMMENT 'unit %', 
	charge_discharge_efficiency DOUBLE DEFAULT NULL COMMENT 'unit %',
    PRIMARY KEY (test_id, barcode, cycle_id)
    -- SET THE DEFAULT VALUES, UNIQUE AND NOT NULL
);