CREATE TABLE `testlab-db`.cycle_casted (
	test_id INT UNSIGNED NOT NULL DEFAULT 0,
	seq_id INT UNSIGNED DEFAULT NULL,
	computer_name VARCHAR(20) DEFAULT NULL,
	chl_id VARCHAR(20) DEFAULT NULL, 
	barcode VARCHAR(60) NOT NULL DEFAULT '',
	cycle_id INT UNSIGNED NOT NULL DEFAULT 0, 
	charge_capacity DOUBLE DEFAULT NULL,
	discharge_capacity DOUBLE DEFAULT NULL,
	charge_energy DOUBLE DEFAULT NULL, 
	discharge_energy DOUBLE DEFAULT NULL,
	net_discharge_capacity DOUBLE DEFAULT NULL, 
	net_discharge_energy DOUBLE DEFAULT NULL, 
	charge_mid_voltage DOUBLE DEFAULT NULL, 
	discharge_mid_voltage DOUBLE DEFAULT NULL,
	batch_no VARCHAR(60) DEFAULT NULL,
	remark VARCHAR(60) DEFAULT NULL,
	soh DOUBLE DEFAULT NULL, 
	specific_charge_capacity DOUBLE DEFAULT NULL, 
	specific_discharge_capacity DOUBLE DEFAULT NULL,
	specific_charge_energy DOUBLE DEFAULT NULL, 
	specific_discharge_energy DOUBLE DEFAULT NULL,
	staring_time BIGINT DEFAULT NULL,
	end_time BIGINT DEFAULT NULL,
	builder VARCHAR(25) DEFAULT NULL,
	active_material DOUBLE DEFAULT NULL, 
	active_material_unit VARCHAR(10) DEFAULT NULL,
	dicharge_capacity_attenuation_rate DOUBLE DEFAULT NULL, 
	discharge_energy_retention_rate DOUBLE DEFAULT NULL, 
	charge_discharge_efficiency DOUBLE DEFAULT NULL,
    PRIMARY KEY (test_id, barcode, cycle_id)
    -- SET THE DEFAULT VALUES, UNIQUE AND NOT NULL
);