CREATE TABLE `testlab-db`.step_casted (
	test_id INT UNSIGNED NOT NULL DEFAULT 0,
	seq_id INT UNSIGNED DEFAULT NULL,
	computer_name VARCHAR(20) DEFAULT NULL COMMENT 'length 20', 
	chl_id VARCHAR(20) DEFAULT NULL COMMENT 'length 20', 
	barcode VARCHAR(60) NOT NULL DEFAULT '' COMMENT 'length 60',
	cycle_id INT UNSIGNED DEFAULT NULL,
	step_num INT UNSIGNED DEFAULT NULL,
	step_id INT UNSIGNED DEFAULT NULL,
	step_type VARCHAR(15) DEFAULT NULL COMMENT 'length 15', 
	step_time BIGINT UNSIGNED DEFAULT NULL,
	charge_energy DOUBLE DEFAULT NULL COMMENT 'unit Wh',
	discharge_energy DOUBLE DEFAULT NULL COMMENT 'unit Wh',
	#chg_mid_voltage varchar(255) 
	charge_capacity DOUBLE DEFAULT NULL COMMENT 'unit Ah',
	discharge_capacity DOUBLE DEFAULT NULL COMMENT 'unit Ah',
	#dc_mid_voltage varchar(255) 
	net_discharge_capacity DOUBLE DEFAULT NULL COMMENT 'unit Ah',
	net_discharge_energy DOUBLE DEFAULT NULL COMMENT 'unit Wh',
	charge_time BIGINT UNSIGNED DEFAULT NULL,
	discharge_time BIGINT UNSIGNED DEFAULT NULL,
	start_voltage DOUBLE DEFAULT NULL COMMENT 'unit V', 
	end_voltage DOUBLE DEFAULT NULL COMMENT 'unit V',
	end_temp DOUBLE DEFAULT NULL COMMENT 'unit ºC',
	batch_no VARCHAR(25) DEFAULT NULL COMMENT 'length 25',  
	remark VARCHAR(60) DEFAULT NULL COMMENT 'length 60',
	step_file_name VARCHAR(150) DEFAULT NULL COMMENT 'length 150',
	starting_time BIGINT DEFAULT NULL, #correct name
	end_time BIGINT DEFAULT NULL, #correct name
    builder VARCHAR(25) DEFAULT NULL COMMENT 'length 25', 
    active_material DOUBLE DEFAULT NULL COMMENT 'unit mg', 
    start_current DOUBLE DEFAULT NULL COMMENT 'unit A', 
    end_current DOUBLE DEFAULT NULL COMMENT 'unit A',
    capacity DOUBLE DEFAULT NULL COMMENT 'unit Ah', 
    energy DOUBLE DEFAULT NULL COMMENT 'unit Wh', 
    first_current DOUBLE DEFAULT NULL COMMENT 'unit A', 
    first_voltage DOUBLE DEFAULT NULL COMMENT 'unit V', 
    nominal_capacity DOUBLE DEFAULT NULL COMMENT 'unit mAh', 
    PRIMARY KEY (test_id, barcode)
)