CREATE TABLE IF NOT EXISTS `channel_status` (
`computer_name` varchar(255) NOT NULL DEFAULT '' COMMENT '',
`equipt_code` varchar(255) NOT NULL DEFAULT '' COMMENT 'Device ID',
`channel_no` varchar(255) NOT NULL DEFAULT '' COMMENT 'Unit ID',
`channel_code` varchar(255) NOT NULL DEFAULT '' COMMENT 'CH ID',
`pc_name` varchar(255) DEFAULT NULL COMMENT 'Computer name',
`barcode` varchar(255) DEFAULT NULL COMMENT 'Barcode',
`step_id` varchar(255) DEFAULT NULL COMMENT 'Step Index',
`cycle_id` varchar(255) DEFAULT NULL COMMENT 'Cycle count',
`step_duration` varchar(255) DEFAULT NULL COMMENT 'Step Time',
`total_duration` varchar(255) DEFAULT NULL COMMENT 'Total Time',
`btsSysState` varchar(255) DEFAULT NULL COMMENT 'Charge and discharge system state',
`voltage` varchar(255) DEFAULT NULL COMMENT 'Voltage',
`current` varchar(255) DEFAULT NULL COMMENT 'Current',
`power` varchar(255) DEFAULT NULL COMMENT 'Power',
`step_capacity` varchar(255) DEFAULT NULL COMMENT 'Capacity',
`total_capacity` varchar(255) DEFAULT NULL COMMENT 'Total capacity',
`step_energy` varchar(255) DEFAULT NULL COMMENT 'Energy',
`total_energy` varchar(255) DEFAULT NULL COMMENT 'Total energy',
`total_charge_capacity` varchar(255) DEFAULT NULL COMMENT 'Total Chg Cap.',
`total_discharge_capacity` varchar(255) DEFAULT NULL COMMENT 'Total DChg Cap.',
`total_charge_energy` varchar(255) DEFAULT NULL COMMENT 'Total Chg Eng.',
`total_discharge_energy` varchar(255) DEFAULT NULL COMMENT 'Total DChg Eng.',
`voltage_setting` varchar(255) DEFAULT NULL COMMENT 'Voltage setting value ',
`current_setting` varchar(255) DEFAULT NULL COMMENT 'Current setting value',
`max_single_voltage` varchar(255) DEFAULT NULL COMMENT 'Aux. Vmax',
`min_single_voltage` varchar(255) DEFAULT NULL COMMENT 'Aux. Vmin',
`max_single_temperature` varchar(255) DEFAULT NULL COMMENT 'Aux. Tmax',
`min_single_temperature` varchar(255) DEFAULT NULL COMMENT 'Aux. Tmin',
`transmit_time` varchar(255) DEFAULT NULL COMMENT 'Date',
`aux_single_voltage` varchar(255) DEFAULT NULL COMMENT 'Aux CH volt.',
`aux_single_temperature` varchar(255) DEFAULT NULL COMMENT 'Aux CH temp.',
`delta_temperature` varchar(255) DEFAULT NULL COMMENT 'ΔTemperature',
`step_name` varchar(255) DEFAULT NULL COMMENT 'Step Name',
`device_IP` varchar(255) DEFAULT NULL COMMENT 'Device IP',
`upload_time` varchar(255) DEFAULT NULL COMMENT 'Upload time',
`end_time` varchar(255) DEFAULT NULL COMMENT 'End time',
PRIMARY KEY ( `computer_name`,`equipt_code`,`channel_no`,`channel_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8