CREATE TABLE IF NOT EXISTS `record` (
`test_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Test ID',
`seq_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'DataPoint',
`computer_name` varchar(255) NOT NULL DEFAULT '' COMMENT '',
`chl_id` varchar(255) NOT NULL DEFAULT '' COMMENT 'CH ID',
`barcode` varchar(255) DEFAULT NULL COMMENT 'Cell bar code',
`cycle_id` varchar(255) DEFAULT NULL COMMENT 'Cycle Index',
`step_num` varchar(255) DEFAULT NULL COMMENT 'Step Number',
`step_id` varchar(255) DEFAULT NULL COMMENT 'Original step',
`record_id` varchar(255) DEFAULT NULL COMMENT 'DataPoint',
`step_type` varchar(255) DEFAULT NULL COMMENT 'Step Name',
`record_time` varchar(255) DEFAULT NULL COMMENT 'Record time',
`voltage` varchar(255) DEFAULT NULL COMMENT 'Voltage',
`current` varchar(255) DEFAULT NULL COMMENT 'Current',
`capacity` varchar(255) DEFAULT NULL COMMENT 'Capacity',
`energy` varchar(255) DEFAULT NULL COMMENT 'Energy',
`power` varchar(255) DEFAULT NULL COMMENT 'Power',
`absolute_time` varchar(255) DEFAULT NULL COMMENT 'Date',
`aux_temperature` varchar(255) DEFAULT NULL COMMENT 'Aux CH temp.',
`batch_no` varchar(255) DEFAULT NULL COMMENT 'Process name',
`remark` varchar(255) DEFAULT NULL COMMENT 'Remarks',
`builder` varchar(255) DEFAULT NULL COMMENT 'Builder',
`active_material` varchar(255) DEFAULT NULL COMMENT 'Active material',
`customize_settings` varchar(255) DEFAULT NULL COMMENT 'Customize settings',
`customize_settings_2` varchar(255) DEFAULT NULL COMMENT 'Customize settings2',
`equipment_remarks` varchar(255) DEFAULT NULL COMMENT 'Equipment remarks',
`total_time` varchar(255) DEFAULT NULL COMMENT 'Total Time',
PRIMARY KEY ( `test_id`,`seq_id`,`computer_name`,`chl_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8