CREATE TABLE IF NOT EXISTS `schedule` (
`test_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Test ID',
`seq_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'DataPoint',
`computer_name` varchar(255) NOT NULL DEFAULT '' COMMENT '',
`chl_id` varchar(255) NOT NULL DEFAULT '' COMMENT 'CH ID',
`barcode` varchar(255) DEFAULT NULL COMMENT 'Cell bar code',
`step_id` varchar(255) DEFAULT NULL COMMENT 'Step Index',
`step_type` varchar(255) DEFAULT NULL COMMENT 'Step Name',
`step_duration` varchar(255) DEFAULT NULL COMMENT 'Step Time',
`setting_voltage` varchar(255) DEFAULT NULL COMMENT 'Voltage',
`setting_rate` varchar(255) DEFAULT NULL COMMENT 'C-rate',
`setting_current` varchar(255) DEFAULT NULL COMMENT 'Current',
`cut_of_rate` varchar(255) DEFAULT NULL COMMENT 'Cut-off C-rate',
`cut_of_current` varchar(255) DEFAULT NULL COMMENT 'Cut-off curr.',
`energy` varchar(255) DEFAULT NULL COMMENT 'Energy',
`DV` varchar(255) DEFAULT NULL COMMENT '-ΔV',
`power` varchar(255) DEFAULT NULL COMMENT 'Power',
`IR` varchar(255) DEFAULT NULL COMMENT 'Resistance',
`capacity` varchar(255) DEFAULT NULL COMMENT 'Capacity',
`recording_conditions` varchar(255) DEFAULT NULL COMMENT 'Record settings',
`aux_record_conditions` varchar(255) DEFAULT NULL COMMENT 'Aux.CH recording condition',
`MaxVi` varchar(255) DEFAULT NULL COMMENT 'Max Vi',
`MinVi` varchar(255) DEFAULT NULL COMMENT 'Min Vi',
`MaxTi` varchar(255) DEFAULT NULL COMMENT 'Max Ti',
`MinTi` varchar(255) DEFAULT NULL COMMENT 'Min Ti',
`record1` varchar(255) DEFAULT NULL COMMENT 'Segment record1',
`record2` varchar(255) DEFAULT NULL COMMENT 'Segment record2',
`starting_time` varchar(255) DEFAULT NULL COMMENT 'Test start time',
`end_time` varchar(255) DEFAULT NULL COMMENT 'Test end time',
`remark` varchar(255) DEFAULT NULL COMMENT 'Remarks',
`P` varchar(255) DEFAULT NULL COMMENT 'P/N',
`Builder` varchar(255) DEFAULT NULL COMMENT 'Builder',
`Active_material` varchar(255) DEFAULT NULL COMMENT 'Active material',
`curoff_voltage` varchar(255) DEFAULT NULL COMMENT 'Cut-off voltage ',
`start_step_ID` varchar(255) DEFAULT NULL COMMENT 'Start step ID',
`cycle_count` varchar(255) DEFAULT NULL COMMENT 'Cycle count',
`upload_time` varchar(255) DEFAULT NULL COMMENT 'Upload time',
`customize_setting` varchar(255) DEFAULT NULL COMMENT 'Customize settings',
`customize_setting_2` varchar(255) DEFAULT NULL COMMENT 'Customize settings2',
`equipment_remarks` varchar(255) DEFAULT NULL COMMENT 'Equipment remarks',
PRIMARY KEY ( `test_id`,`seq_id`,`computer_name`,`chl_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8