CREATE TABLE IF NOT EXISTS `step` (
`test_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Test ID',
`seq_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'DataPoint',
`computer_name` varchar(255) NOT NULL DEFAULT '' COMMENT '',
`chl_id` varchar(255) NOT NULL DEFAULT '' COMMENT 'CH ID',
`barcode` varchar(255) DEFAULT NULL COMMENT 'Cell bar code',
`cycle_id` varchar(255) DEFAULT NULL COMMENT 'Cycle Index',
`step_num` varchar(255) DEFAULT NULL COMMENT 'Step Number',
`step_id` varchar(255) DEFAULT NULL COMMENT 'Original step',
`step_type` varchar(255) DEFAULT NULL COMMENT 'Step Name',
`step_time` varchar(255) DEFAULT NULL COMMENT 'Step Time',
`step_file_name` varchar(255) DEFAULT NULL COMMENT 'Step file name',
`charge_energy` varchar(255) DEFAULT NULL COMMENT 'Chg. Energy',
`discharge_energy` varchar(255) DEFAULT NULL COMMENT 'DChg. Energy',
`charge_capacity` varchar(255) DEFAULT NULL COMMENT 'Chg. Cap.',
`discharge_capacity` varchar(255) DEFAULT NULL COMMENT 'DChg. Cap.',
`net_discharge_capacity` varchar(255) DEFAULT NULL COMMENT 'Net DChg. Cap.',
`net_discharge_energy` varchar(255) DEFAULT NULL COMMENT 'Net DChg. Energy',
`charge_time` varchar(255) DEFAULT NULL COMMENT 'Chg. Time',
`discharge_time` varchar(255) DEFAULT NULL COMMENT 'DChg. Time',
`start_voltage` varchar(255) DEFAULT NULL COMMENT 'Oneset Volt.',
`end_voltage` varchar(255) DEFAULT NULL COMMENT 'End Voltage',
`end_temp` varchar(255) DEFAULT NULL COMMENT 'End T',
`batch_no` varchar(255) DEFAULT NULL COMMENT 'Process name',
`starting_time` varchar(255) DEFAULT NULL COMMENT 'Starting time',
`end_time` varchar(255) DEFAULT NULL COMMENT 'End time',
`remark` varchar(255) DEFAULT NULL COMMENT 'Remarks',
`builder` varchar(255) DEFAULT NULL COMMENT 'Builder',
`active_material` varchar(255) DEFAULT NULL COMMENT 'Active material',
`start_current` varchar(255) DEFAULT NULL COMMENT 'Starting current',
`end_current` varchar(255) DEFAULT NULL COMMENT 'End Current',
`capacity` varchar(255) DEFAULT NULL COMMENT 'Capacity',
`energy` varchar(255) DEFAULT NULL COMMENT 'Energy',
`first_current` varchar(255) DEFAULT NULL COMMENT 'First current at non-zero time',
`first_voltage` varchar(255) DEFAULT NULL COMMENT 'First voltage at non-zero time',
`nominal_capacity` varchar(255) DEFAULT NULL COMMENT 'Nominal capacity',
PRIMARY KEY ( `test_id`,`seq_id`,`computer_name`,`chl_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8